# Arithmetic Operations

## 1 - Dimensional Array

In [2]:
import numpy as np
var1 = np.array([45,56,14,89]);
new = var1 + 66;
print(var1);
print(new);

[45 56 14 89]
[111 122  80 155]


In [4]:
var1 = np.array([45,65,36,58]);
var2 = np.array([58,69,32,25]);
new = var1 + var2;
print(var1);
print(var2);
print(new);

[45 65 36 58]
[58 69 32 25]
[103 134  68  83]


In [5]:
var1 = np.array([45,65,36,58]);
var2 = np.array([58,69,32,25]);
new = np.add(var1, var2);
print(var1);
print(var2);
print(new);

[45 65 36 58]
[58 69 32 25]
[103 134  68  83]


In [6]:
var1 = np.array([45,65,36,58]);
var2 = np.array([58,69,32,25]);
new = var1 % 2;

print(var1);
print(var2);
print(new);

[45 65 36 58]
[58 69 32 25]
[1 1 0 0]


In [7]:
var1 = np.array([45,65,36,58]);
var2 = np.array([58,69,32,25]);
new = np.add(var1, var2);
multiply = np.multiply(var1, var2);
print(var1);
print(var2);
print(new);
print(multiply);

[45 65 36 58]
[58 69 32 25]
[103 134  68  83]
[2610 4485 1152 1450]


## 2 - Dimensional Array

In [9]:
var = np.array([[54,25,78],[96,36,77]]);
new = var + 6;
print(var);
print(new);

[[54 25 78]
 [96 36 77]]
[[ 60  31  84]
 [102  42  83]]


In [10]:
var = np.array([[54,25,78],[96,36,77]]);
new = np.reciprocal(var);
print(var);
print(new);

[[54 25 78]
 [96 36 77]]
[[0 0 0]
 [0 0 0]]


## Arithmetic Functions

In [15]:
var_1 = np.array([56,25,35,78]);
new = np.min(var_1);
new_2 = np.max(var);
print(new, np.argmin(var));
print(new_2, np.argmax(var));

25 1
96 3


In [18]:
var_3 = np.array([[2, 5, 6, 8],[7, 6, 9, 3]]);
print(np.min(var_3, axis=0));
print(np.max(var_3, axis=1));

[2 5 6 3]
[8 9]


In [19]:
var_4 = np.array([45, 63, 89]);
new = np.cumsum(var_4);
print(new);

[ 45 108 197]
