## Array 

In [3]:
import numpy as np
l =[]
for i in range(1,5):
    int_1 = int(input("Enter: "))
    l.append(int_1)
y = np.array(l);
print(y);
#print(np.array(l));
print(y.ndim);

Enter:  7
Enter:  8
Enter:  55
Enter:  5


[ 7  8 55  5]
1


In [6]:
arr2 = np.array([[45,56,89,25],[78,36,62,59]])
print(arr2);
print("The dimension of the given array is",arr2.ndim);

[[45 56 89 25]
 [78 36 62 59]]
The dimension of the given array is 2


In [8]:
arr3 = np.array([[[45,36,96],[56,25,36], [45,89,36]]])
print(arr3);
print("The dimension of the given array is",arr3.ndim);

[[[45 36 96]
  [56 25 36]
  [45 89 36]]]
The dimension of the given array is 3


In [9]:
arr4 = np.array([56,23,45,36],ndmin = 10)
print(arr4);
print("The dimension of the given array is", arr4.ndim);

[[[[[[[[[[56 23 45 36]]]]]]]]]]
The dimension of the given array is 10


# Zeros

In [11]:
arr_zero = np.zeros(4);
print(arr_zero);

[0. 0. 0. 0.]


In [14]:
arr_zero = np.zeros((4,6));
print(arr_zero);

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
arr_ones = np.ones(4);
print(arr_ones);

[1. 1. 1. 1.]


# Empty

In [18]:
arr_emp = np.empty(6);
print(arr_emp);

[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000  2.22044605e-016
  2.22507386e-308  4.94065646e-324]


# Range

In [19]:
arr_rn = np.arange(5);
print(arr_rn);

[0 1 2 3 4]


# Diagonal

In [21]:
arr_diag = np.eye(4);
print(arr_diag);

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
arr_diag = np.eye(3,5);
print(arr_diag);

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Specified Interval 
## linspace

In [24]:
arr_lin = np.linspace(0,10, num = 5);
print(arr_lin);

[ 0.   2.5  5.   7.5 10. ]
