# Data Type

In [2]:
import numpy as np
var1 = np.array([4, 5, 6, 2]);
print(var1);
print("Data type:",var1.dtype);

[4 5 6 2]
Data type: int64


In [3]:
var2 = np.array([5.6,3.2, 6.6, 9.8]);
print(var2);
print("Data Type:", var2.dtype);

[5.6 3.2 6.6 9.8]
Data Type: float64


In [6]:
var3 = np.array(["apple", "ball", "cat","dog"]);
print(var3);
print("Data Type:", var3.dtype);

['apple' 'ball' 'cat' 'dog']
Data Type: <U5


In [7]:
var3 = np.array(["apple", "ball", "cat","dog", 5, 6]);
print(var3);
print("Data Type:", var3.dtype);

['apple' 'ball' 'cat' 'dog' '5' '6']
Data Type: <U21


In [9]:
var4 = np.array([1,2,3,4]);
print(var4);
print("Data Type:", var4.dtype);

[1 2 3 4]
Data Type: int64


## Data Type Conversion

In [11]:
# Conver data type
var4 = np.array([1,2,3,4], dtype = np.int8);
print(var4);
print("Data Type:", var4.dtype);

[1 2 3 4]
Data Type: int8


In [12]:
# Conver data type
var4 = np.array([1,2,3,4], dtype = "f");
print(var4);
print("Data Type:", var4.dtype);

[1. 2. 3. 4.]
Data Type: float32


In [16]:
x1 = np.array([5,6,8,9]);
new = np.float32(x1);
new_2 = np.intc(new);

new_3 = x1.astype(float);
print(x1.dtype);
print(new.dtype);
print(new_2.dtype);
print(new_3.dtype);

print(x1);
print(new);
print(new_2);
print(new_3);

int64
float32
int32
float64
[5 6 8 9]
[5. 6. 8. 9.]
[5 6 8 9]
[5. 6. 8. 9.]
