## Indexing

In [2]:
import numpy as np

In [3]:
var = np.array([45,65,989,25]);
print(var);
print(var[2]);


[ 45  65 989  25]
989


In [6]:
var = np.array([[56,36,52,89],[96,36,69,45]]);
print(var);
print(var[1,3]);

[[56 36 52 89]
 [96 36 69 45]]
45


In [7]:
var = np.array([[[45,36,89,25],[86,96,65,32]]]);
print(var);
print(var[0,1,2]);

[[[45 36 89 25]
  [86 96 65 32]]]
65


## Slicing

In [8]:
var = np.array([78,56,96,36,46]);
print(var);
print(var[1:3]);


[78 56 96 36 46]
[56 96]


In [9]:
var = np.array([78,56,96,36,46]);
print(var);
print(var[1:6:2]);


[78 56 96 36 46]
[56 36]


In [10]:
var = np.array([[45,63,98,25],[78,36,95,24]]);
print(var);
print(var[1,1:3]);

[[45 63 98 25]
 [78 36 95 24]]
[36 95]


In [11]:
var = np.array([[[56,35,24,15],[47,56,32,96],[15,37,25,36]]])
print(var);
print(var[0,2,1:3]);

[[[56 35 24 15]
  [47 56 32 96]
  [15 37 25 36]]]
[37 25]
