## Iterations

In [2]:
import numpy as np

In [3]:
var = np.array([45,36,78,96,35]);
print(var);


[45 36 78 96 35]


In [4]:
var = np.array([12,45,63,78,96]);
print(var);
for i in var:
    print(i);

[12 45 63 78 96]
12
45
63
78
96


In [6]:
var =  np.array([[45,12,96,36],[45,96,31,75],[47,62,19,38]]);
print(var);
for i in var:
    for k in i:
        print(k);

[[45 12 96 36]
 [45 96 31 75]
 [47 62 19 38]]
45
12
96
36
45
96
31
75
47
62
19
38


In [9]:
var =  np.array([[[45,12,96,36],[45,96,31,75],[47,62,19,38]]]);
print(var);
for i in var:
    for k in i:
        for j in k:
            print(j);

[[[45 12 96 36]
  [45 96 31 75]
  [47 62 19 38]]]
45
12
96
36
45
96
31
75
47
62
19
38


## nditer()

In [12]:
var = np.array([45,25,63,78]);
print(var);
for i in np.nditer(var):
    print(i);

[45 25 63 78]
45
25
63
78


In [24]:
var = np.array([[[45,25,63,78],[45,36,95,78]]]);
print(var);
for i in np.nditer(var, flags=['buffered'],op_dtypes = ['S10'], casting="unsafe"):
    print(i);

[[[45 25 63 78]
  [45 36 95 78]]]
np.bytes_(b'45')
np.bytes_(b'25')
np.bytes_(b'63')
np.bytes_(b'78')
np.bytes_(b'45')
np.bytes_(b'36')
np.bytes_(b'95')
np.bytes_(b'78')


In [ ]:
## enumerate (iterate with 

In [25]:
var = np.array([45,25,63,78]);
print(var);
for i,d in np.ndenumerate(var):
    print(i,d);

[45 25 63 78]
(0,) 45
(1,) 25
(2,) 63
(3,) 78
