# Matrix

In [1]:
import numpy as np

In [26]:
#var_1 = np.matrix([[1,5,6,2],[5,6,8,6]]);
#var_2 = np.matrix([[4,3,6,7],[8,9,6,7]]);
var_1 = np.matrix([[1,2],[5,7]]);
var_2 = np.matrix([[4,3],[8,9]]);

print(var_1);
print(var_2);
print(type(var_1));
print("Addition");
print(var_1 + var_2);
print("Multiplication");
print(var_1.dot(var_2));
print("Transpose");
print(np.transpose(var_1));
print("Swapaxes");
print(np.swapaxes(var_2, 0, 1));

var_3 = np.matrix([[45,25],[78,14]])
print(var_3);
print("Inverse");
print(np.linalg.inv(var_3));

print("power of matrix");
print(np.linalg.matrix_power(var_3, 0)); # gives identity matrix
print(np.linalg.matrix_power(var_3, 2));
print(np.linalg.matrix_power(var_3, -2));# gives inverse*power
print("Determinant");
print(np.linalg.det(var_3));

[[1 2]
 [5 7]]
[[4 3]
 [8 9]]
<class 'numpy.matrix'>
Addition
[[ 5  5]
 [13 16]]
Multiplication
[[20 21]
 [76 78]]
Transpose
[[1 5]
 [2 7]]
Swapaxes
[[4 8]
 [3 9]]
[[45 25]
 [78 14]]
Inverse
[[-0.01060606  0.01893939]
 [ 0.05909091 -0.03409091]]
power of matrix
[[1 0]
 [0 1]]
[[3975 1475]
 [4602 2146]]
[[ 0.00123163 -0.00084653]
 [-0.00264118  0.00228134]]
Determinant
-1320.0


# Array

In [8]:
var_1 = np.array([[1,5,6,2],[5,6,8,6]]);
var_2 = np.array([[4,3,6,7],[8,9,6,7]]);

print(var_1);
print(var_2);
print(type(var_1));
print("Addition");
print(var_1 + var_2);
print("Multiplication");
print(var_1*var_2);

[[1 5 6 2]
 [5 6 8 6]]
[[4 3 6 7]
 [8 9 6 7]]
<class 'numpy.ndarray'>
Addition
[[ 5  8 12  9]
 [13 15 14 13]]
Multiplication
[[ 4 15 36 14]
 [40 54 48 42]]
