# Concatenation

In [2]:
import numpy as np


In [9]:
var_1 = np.array([45, 63,98,65]);
var_2 = np.array([45, 21, 34, 78]);
print(var_1);
print(var_2);
print("The concatenated array");
new = np.concatenate((var_1,var_2));
new_2 = np.stack((var_1,var_2),axis=1);# use stack with axis to convert 2D array with merge
print(new);
print(new_2);

[45 63 98 65]
[45 21 34 78]
The concatenated array
[45 63 98 65 45 21 34 78]
[[45 45]
 [63 21]
 [98 34]
 [65 78]]


In [7]:
var_1 = np.array([[45,26,35],[78,63,95]])
var_2 = np.array([[45,25,36],[15,28,36]])
print(var_1);
print(var_2);
print("The concatenated array");
new_arr_1 = np.concatenate((var_1,var_2), axis = 1);# Along rows
new_arr_2 = np.concatenate((var_1,var_2), axis = 0);# Along columns
print(new_arr_1);
print(new_arr_2);

[[45 26 35]
 [78 63 95]]
[[45 25 36]
 [15 28 36]]
The concatenated array
[[45 26 35 45 25 36]
 [78 63 95 15 28 36]]
[[45 26 35]
 [78 63 95]
 [45 25 36]
 [15 28 36]]


# Stack

In [10]:
var_1 = np.array([45, 63,98,65]);
var_2 = np.array([45, 21, 34, 78]);
print(var_1);
print(var_2);
print("The concatenated array");
new = np.concatenate((var_1,var_2));
new_2 = np.stack((var_1,var_2),axis=1);# use stack with axis to convert 2D array with merge
print(new);
print(new_2);

[45 63 98 65]
[45 21 34 78]
The concatenated array
[45 63 98 65 45 21 34 78]
[[45 45]
 [63 21]
 [98 34]
 [65 78]]


In [11]:
var_1 = np.array([45, 63,98,65]);
var_2 = np.array([45, 21, 34, 78]);
print(var_1);
print(var_2);
print("The concatenated array");
new = np.concatenate((var_1,var_2));
new_2 = np.hstack((var_1,var_2));# horizontally merge
new_3 = np.vstack((var_1,var_2));# vertically merge
new_4 = np.dstack((var_1,var_2));# depth/height along merge
print(new);
print("Horizontal:",new_2);
print("Vertical:", new_3);
print("depth:", new_4);

[45 63 98 65]
[45 21 34 78]
The concatenated array
[45 63 98 65 45 21 34 78]
Horizontal: [45 63 98 65 45 21 34 78]
Vertical: [[45 63 98 65]
 [45 21 34 78]]
depth: [[[45 45]
  [63 21]
  [98 34]
  [65 78]]]


## Split array

In [14]:
var = np.array([45,36,58,25]);
print(var);
arr = np.array_split(var, 3);
print("Splitted array");
print(arr);
print(arr[1]);
print(type(arr));


[45 36 58 25]
Splitted array
[array([45, 36]), array([58]), array([25])]
[58]
<class 'list'>


In [15]:
var = np.array([[45,36],[58,25],[58,69]]);
print(var);
arr = np.array_split(var, 3);
print("Splitted array");
print(arr);
print(arr[1]);
print(type(arr));

[[45 36]
 [58 25]
 [58 69]]
Splitted array
[array([[45, 36]]), array([[58, 25]]), array([[58, 69]])]
[[58 25]]
<class 'list'>


In [18]:
var = np.array([[45,36],[58,25],[58,69]]);
print(var);
arr = np.array_split(var, 3);
arr_2 = np.array_split(var, 3, axis=1);
print("Splitted array");
print(arr);
print(arr[1]);
print(type(arr));

print();
print(arr_2);

[[45 36]
 [58 25]
 [58 69]]
Splitted array
[array([[45, 36]]), array([[58, 25]]), array([[58, 69]])]
[[58 25]]
<class 'list'>

[array([[45],
       [58],
       [58]]), array([[36],
       [25],
       [69]]), array([], shape=(3, 0), dtype=int64)]
