## Shuffle

In [1]:
import numpy as np


In [4]:
var = np.array([1,2,3,4,5]);
np.random.shuffle(var);
print(var)

[2 4 3 5 1]


# Unique

In [6]:
var_2 = np.array([1,1,1,2,2,5,8,6,3]);
new = np.unique(var_2, return_index=True, return_counts=True);
print(var_2);
print(new);

[1 1 1 2 2 5 8 6 3]
(array([1, 2, 3, 5, 6, 8]), array([0, 3, 8, 5, 7, 6]), array([3, 2, 1, 1, 1, 1]))


# Resize

In [7]:
var_3 = np.array([45,65,25,36]);
y = np.resize(var_3, (3,2));
print(y);

[[45 65]
 [25 36]
 [45 65]]


# flatten

In [10]:
var_3 = np.array([45,65,25,36]);
y = np.resize(var_3, (3,2));
print(y);
print(y.flatten(order="F"));
print(np.ravel(y, order="A"));

[[45 65]
 [25 36]
 [45 65]]
[45 25 45 65 36 65]
[45 65 25 36 45 65]


# Insert

In [12]:
arr = np.array([45,25,15,96,36,78]);
print(arr);
new_arr = np.insert(arr, (2,5), 99);
new_arr_2 = np.append(arr, 6.56);
print(new_arr);
print(new_arr_2);

[45 25 15 96 36 78]
[45 25 99 15 96 36 99 78]
[45.   25.   15.   96.   36.   78.    6.56]


In [19]:
arr_2 = np.array([[45,23,69,11],[56,98,36,75]]);
print(arr_2);
new_arr = np.insert(arr_2, 2, [88,55,86,66],axis=0);
new_arr_2 = np.append(arr_2, [[45,63,89,22]], axis = 0);
print(new_arr);
print(new_arr_2);

[[45 23 69 11]
 [56 98 36 75]]
[[45 23 69 11]
 [56 98 36 75]
 [88 55 86 66]]
[[45 23 69 11]
 [56 98 36 75]
 [45 63 89 22]]


# Delete

In [21]:
var = np.array([12,15,13,17]);
print(var);
new_var = np.delete(var, 2);
print(new_var);

[12 15 13 17]
[12 15 17]
