# Searching

In [24]:
import numpy as np


In [25]:
var = np.array([56,24,63,87,69]);
print(var);
x = np.where((var%2) == 0);
print(x);


[56 24 63 87 69]
(array([0, 1]),)


In [26]:
var_2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]);
x2 = np.searchsorted(var_2, 6);
x3 = np.searchsorted(var_2, 6, side="right");
print(var_2);
print(x2);
print(x3);

[ 1  2  3  4  5  6  7  8  9 10 11 12]
5
6


In [22]:
var_2 = np.array([1,2,3,4,5,6,10,11,12]);
x = np.searchsorted(var_2,[7,8,9]);
print(x);

[6 6 6]


## Sorting

In [23]:
arr = np.array([[23,14,89],[45,89,12]]);
print(arr);
print("After sorting");
print(np.sort(arr));

[[23 14 89]
 [45 89 12]]
After sorting
[[14 23 89]
 [12 45 89]]


In [16]:
alpha = np.array(["s","a","z","t"]);
print(alpha);
print("After sorting");
print(np.sort(alpha));

['s' 'a' 'z' 't']
After sorting
['a' 's' 't' 'z']


# Filter Array

In [18]:
var_3 = np.array(["a","s","d","f"])
f = [True, False, False, True];
new_a = var_3[f];
print(new_a);
print(type(new_a));

['a' 'f']
<class 'numpy.ndarray'>
