## Shape

In [1]:
import numpy as np
var = np.array([45, 63, 98, 25]);
print(var);
print(var.shape);

[45 63 98 25]
(4,)


In [2]:
var_2 = np.array([[54,8,6,],[8,6,9]]);
print(var_2);
print(var_2.shape);

[[54  8  6]
 [ 8  6  9]]
(2, 3)


In [4]:
var_3 = np.array([58,69,32,65], ndmin = 10);
print(var_3);
print(var_3.ndim);
print(var_3.shape);

[[[[[[[[[[58 69 32 65]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


## Reshape

In [7]:
var_4 = np.array([56, 45, 89,46, 3, 2]);
print(var_4);
print(var_4.ndim);
new = var_4.reshape(2, 3);
print(new);
print(new.ndim);

[56 45 89 46  3  2]
1
[[56 45 89]
 [46  3  2]]
2


In [13]:
var_4 = np.array([56, 45, 89,46, 3, 2,5,8,9, 5, 6, 8]);
print(var_4);
print(var_4.ndim);
# reshape(depth, rows, columns)
#total elements = depth*rows*columns
new = var_4.reshape(2, 3, 2);
print(new);
print(new.ndim);
print(new.shape);

# convert into ond dimension array again
one_d = new.reshape(-1);
print(one_d);
print(one_d.shape);

[56 45 89 46  3  2  5  8  9  5  6  8]
1
[[[56 45]
  [89 46]
  [ 3  2]]

 [[ 5  8]
  [ 9  5]
  [ 6  8]]]
3
(2, 3, 2)
[56 45 89 46  3  2  5  8  9  5  6  8]
(12,)


,## Broadcasting
,,### Broadcasting lets NumPy perform operations on arrays of different shapes without copying data and element-wise, efficiently.

In [14]:
var_1 = np.array([89,36,15,96,25]);
var_2 = np.array([5,6,8,9,6]);
new = var_1 + var_2;
print(new);

[ 94  42  23 105  31]


In [22]:
var_1 = np.array([89,36,15,96,25]);
var_2 = np.array([[5],[77],[96],[58],[36]]);
print(var_1);
print(var_2);
new = var_1 + var_2;
print("Addition");
print(new);
print(new.shape);
print(new.ndim);
print("Multiplication");
print(var_1 * var_2);
print("Division");
print(var_1 / var_2);

[89 36 15 96 25]
[[ 5]
 [77]
 [96]
 [58]
 [36]]
Addition
[[ 94  41  20 101  30]
 [166 113  92 173 102]
 [185 132 111 192 121]
 [147  94  73 154  83]
 [125  72  51 132  61]]
(5, 5)
2
Multiplication
[[ 445  180   75  480  125]
 [6853 2772 1155 7392 1925]
 [8544 3456 1440 9216 2400]
 [5162 2088  870 5568 1450]
 [3204 1296  540 3456  900]]
Division
[[17.8         7.2         3.         19.2         5.        ]
 [ 1.15584416  0.46753247  0.19480519  1.24675325  0.32467532]
 [ 0.92708333  0.375       0.15625     1.          0.26041667]
 [ 1.53448276  0.62068966  0.25862069  1.65517241  0.43103448]
 [ 2.47222222  1.          0.41666667  2.66666667  0.69444444]]
